server{
    listen 8081;
    server_name localhost;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    gzip on;
    gzip_types text/plain application/javascript application/x-javascript text/css application/json;
    # location ~* \.(css|json|js)$ {
    #     # expires 1y;
    #     # add_header Cache-Control "max-age=31536000";
    # }
}