server{
    listen 8083;
    server_name localhost;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
        # CORS 头 - 允许跨域访问
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, PATCH, OPTIONS";
        add_header Access-Control-Allow-Headers "X-Requested-With, content-type, Authorization";
    }
    gzip on;
    gzip_types text/plain application/javascript application/x-javascript text/css application/json;
}
